//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiLAGen.Client
{
    
    
    [Tecan.Sila2.SilaFeatureAttribute(true, "contracts")]
    [Tecan.Sila2.SilaIdentifierAttribute("TestService")]
    [Tecan.Sila2.SilaDisplayNameAttribute("Test Service")]
    public partial interface ITestService
    {
        
        void Initialize();
        
        [Tecan.Sila2.ObservableAttribute()]
        Tecan.Sila2.IObservableCommand CancelCommandWorks();
        
        [Tecan.Sila2.ObservableAttribute()]
        Tecan.Sila2.IIntermediateObservableCommand<string> ObservableIntermediateCommandWithCancellation();
    }
}
